#                1           2           3           4
transformation: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]
adaption: "mergemesh"
number_of_scans: 1
preserve_float: True
voxel_size: 0.05
batch_interval: 10
#              xmin xmax ymin ymax zmin zmax
voxel_bounds: [-50, 50, -50, 50, -5, 5]
ignore: []
moving: []
labels:
  0: "car"
  1: "bicycle"
  2: "motorcycle"
  3: "truck"
  4: "other-vehicle"
  5: "person"
  6: "bicyclist"
  7: "motorcyclist"
  8: "road"
  9: "parking"
  10: "sidewalk"
  11: "other-ground"
  12: "building"
  13: "fence"
  14: "vegetation"
  15: "trunk"
  16: "terrain"
  17: "pole"
  18: "traffic-sign"
color_map: # bgr
  0: [245, 150, 100]
  1: [245, 230, 100]
  2: [150, 60, 30]
  3: [180, 30, 80]
  4: [255, 0, 0]
  5: [30, 30, 255]
  6: [200, 40, 255]
  7: [90, 30, 150]
  8: [255, 0, 255]
  9: [255, 150, 255]
  10: [75, 0, 75]
  11: [75, 0, 175]
  12: [0, 200, 255]
  13: [50, 120, 255]
  14: [0, 175, 0]
  15: [0, 60, 135]
  16: [80, 240, 150]
  17: [150, 240, 255]
  18: [0, 0, 255]
