#                1           2           3           4
transformation: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]
adaption: "mergemesh"
number_of_scans: 1
preserve_float: True
voxel_size: 0.05
batch_interval: 10
#              xmin xmax ymin ymax zmin zmax
voxel_bounds: [-50, 50, -50, 50, -5, 5]
ignore: [0, 31]
moving:
  [
    202,
    203,
    204,
    205,
    206,
    207,
    208,
    214,
    215,
    216,
    217,
    218,
    219,
    220,
    221,
    222,
    223,
  ]
labels:
  0: "noise"
  1: "animal"
  2: "human.pedestrian.adult"
  3: "human.pedestrian.child"
  4: "human.pedestrian.construction_worker"
  5: "human.pedestrian.personal_mobility"
  6: "human.pedestrian.police_officer"
  7: "human.pedestrian.stroller"
  8: "human.pedestrian.wheelchair"
  9: "movable_object.barrier"
  10: "movable_object.debris"
  11: "movable_object.pushable_pullable"
  12: "movable_object.trafficcone"
  13: "static_object.bicycle_rack"
  14: "vehicle.bicycle"
  15: "vehicle.bus.bendy"
  16: "vehicle.bus.rigid"
  17: "vehicle.car"
  18: "vehicle.construction"
  19: "vehicle.emergency.ambulance"
  20: "vehicle.emergency.police"
  21: "vehicle.motorcycle"
  22: "vehicle.trailer"
  23: "vehicle.truck"
  24: "flat.driveable_surface"
  25: "flat.other"
  26: "flat.sidewalk"
  27: "flat.terrain"
  28: "static.manmade"
  29: "static.other"
  30: "static.vegetation"
  31: "vehicle.ego"
  202: "human.pedestrian.adult.moving"
  203: "human.pedestrian.child.moving"
  204: "human.pedestrian.construction_worker.moving"
  205: "human.pedestrian.personal_mobility.moving"
  206: "human.pedestrian.police_officer.moving"
  207: "human.pedestrian.stroller.moving"
  208: "human.pedestrian.wheelchair.moving"
  214: "vehicle.bicycle.moving"
  215: "vehicle.bus.bendy.moving"
  216: "vehicle.bus.rigid.moving"
  217: "vehicle.car.moving"
  218: "vehicle.construction.moving"
  219: "vehicle.emergency.ambulance.moving"
  220: "vehicle.emergency.police.moving"
  221: "vehicle.motorcycle.moving"
  222: "vehicle.trailer.moving"
  223: "vehicle.truck.moving"
color_map: # bgr #original nuScenes colors below
  0: [0, 0, 0]
  1: [0, 0, 0]
  2: [30, 30, 255]
  3: [30, 30, 255]
  4: [30, 30, 255]
  5: [0, 0, 0]
  6: [30, 30, 255]
  7: [0, 0, 0]
  8: [0, 0, 0]
  9: [0, 200, 255]
  10: [0, 0, 0]
  11: [0, 0, 0]
  12: [0, 200, 255]
  13: [0, 0, 0]
  14: [245, 230, 100]
  15:	[180, 30, 80]
  16:	[180, 30, 80]
  17: [245, 150, 100]
  18:	[180, 30, 80]
  19: [0, 0, 0]
  20: [0, 0, 0]
  21: [150, 60, 30]
  22: [180, 30, 80]
  23: [180, 30, 80]
  24: [255, 0, 255]
  25: [75, 0, 175]
  26: [175, 0, 75]
  27: [80, 240, 150]
  28: [0, 200, 255]
  29: [0, 0, 0]
  30: [0, 175, 0]
  31: [0, 0, 0]
  32: [200, 200, 200]
  202: [30, 30, 255]
  203: [30, 30, 255]
  204: [30, 30, 255]
  205: [0, 0, 0]
  206: [30, 30, 255]
  207: [0, 0, 0]
  208: [0, 0, 0]
  214: [245, 230, 100]
  215: [180, 30, 80]
  216: [180, 30, 80]
  217: [245, 150, 100]
  218: [180, 30, 80]
  219: [0, 0, 0]
  220: [0, 0, 0]
  221: [150, 60, 30]
  222: [180, 30, 80]
  223: [180, 30, 80]
#  1: [75, 0, 75]
#  2: [255, 30, 30]
#  3: [255, 40, 200]
#  4: [150, 30, 90]
#  5: [255, 30, 30]
#  6: [255, 30, 30]
#  7: [255, 30, 30]
#  8: [255, 30, 30]
#  9: [255, 240, 150]
#  10: [255, 240, 150]
#  11: [255, 240, 150]
#  12: [255, 240, 150]
#  13: [100, 230, 245]
#  14: [100, 80, 250]
#  15: [100, 80, 250]
#  16: [100, 150, 245]
#  17: [0, 0, 255]
#  18: [10, 10, 240]
#  19: [30, 30, 220]
#  20: [30, 60, 150]
#  21: [255, 240, 150]
#  22: [80, 30, 180]
#  23: [50, 255, 255]
#  24: [60, 60, 60]
#  25: [75, 0, 175]
#  26: [75, 0, 75]
#  27: [80, 240, 150]
#  28: [0, 200, 255]
#  29: [0, 150, 255]
#  30: [0, 175, 0]
#  31: [0, 0, 255]
#  32: [245, 150, 100]
